[package]
name = "plum_lang"
version = "0.0.1"
edition = "2018"

[[bin]]
name = "plum"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
